import { Button, VerticalBox , ListView, TextEdit,StandardTableView} from "std-widgets.slint";
export component AppWindow inherits Window {
    max_width: 1024px;
    max_height: 768px;
    min_width: 1024px;
    min_height: 768px;
    background: #fff;
    in property <string> version <=> self.title;
    out property <string> connInfo ;
    in property <[[StandardListViewItem]]> model;
    VerticalBox {
        padding: 0px;
        StandardTableView { 
            width: parent.width;
            vertical-stretch: 6;
 
            columns: [
                { title: "识别码" },
                { title: "IP" },
                { title: "分辨率" },
            ];
           rows: root.model;
        }
        Rectangle {
            width: parent.width;
            vertical-stretch: 4;
            info:=TextEdit {
                font-size: 12px;
                width: parent.width;
                height: parent.height;
                read-only:true;
                has-focus: false;
                text: root.connInfo;
            }
        }
    }

    public function conn_Info(s:string){
        root.connInfo = root.connInfo + "\n" + s;
    }
 
}
