import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    min-width: 1024px;
    min-height: 768px;
    in-out property<int> counter: 42;
    in property <image> video-frame <=> image.source;
 
    callback start();
    callback stop();

    VerticalBox {
        image:=Image {
            width: parent.width;
            vertical-stretch: 0;
        }
        HorizontalLayout {
            vertical-stretch: 0;
            Button {
                height: 80px;
                text: "start";
                clicked => {
                    root.start();
                }
            }
            Button {
                height: 80px;
                text: "stop";
                clicked => {
                    root.stop();
                }
            }
        }
    }
}
